# Generated by Django 5.1.2 on 2024-12-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='duration_mins',
            new_name='duration_hrs',
        ),
    ]
