# Generated by Django 5.1.2 on 2024-12-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recurringevent_alter_account_sleep_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringEvent',
        ),
    ]
